# element_wise operation

In [1]:
def naive_relu(x) :
    assert len(x.shape) == 2 #assert condition을 만족하지 않으면 에러!
    
    x = x.copy()
    for i in range(x.shape[0]) :
        for j in range(x.shape[1]) :
            x[i,j] = max(x[i,j], 0)
            
    return x

In [2]:
def naive_add(x,y) :
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]) :
        for j in range(x.shape[1]) :
            x[i,j] += y[i,j]
            
    return x

In [18]:
import numpy as np
x = np.array([[1,2,-56,4],
            [32,0,57,-4522]])

y = np.array([[34,786,934,34],
            [-45,-12,45,25]])

In [19]:
naive_relu(x)

array([[ 1,  2,  0,  4],
       [32,  0, 57,  0]])

In [20]:
np.maximum(x,0)

array([[ 1,  2,  0,  4],
       [32,  0, 57,  0]])

In [24]:
naive_add(x,y)

array([[   35,   788,   878,    38],
       [  -13,   -12,   102, -4497]])

In [23]:
x+y

array([[   35,   788,   878,    38],
       [  -13,   -12,   102, -4497]])

# broadcasting
- 메모리 수준이 아니라 알고리즘 수준에서 일어난다


1. 큰 텐서의 ndim에 맞도록 작은 테넛에 브로드캐스팅 축이라고 부르는 축이 추가
2. 작은 텐서가 새 축을 따라서 큰 테넛의 크기에 맞도록 반복

![image](https://files.realpython.com/media/broadcasting.084a0e28dea8.jpg)

In [31]:
def naive_add_matrix_and_vector(x,y) :
    assert len(x.shape) == 2 #x - 2D tesnsor
    assert len(y.shape) == 1 #y - numpy vector
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]) :
        for j in range(x.shape[1]) :
            x[i,j] += y[j]
            
    return x

In [32]:
x

array([[    1,     2,   -56,     4],
       [   32,     0,    57, -4522]])

In [33]:
y = np.array([1,436,9,4])
y

array([  1, 436,   9,   4])

In [34]:
naive_add_matrix_and_vector(x,y)

array([[    2,   438,   -47,     8],
       [   33,   436,    66, -4518]])

In [36]:
x+y

array([[    2,   438,   -47,     8],
       [   33,   436,    66, -4518]])

In [39]:
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))

z = np.maximum(x,y) #after broadcasting, compare and return maximum
z.shape

(64, 3, 32, 10)

# tensor product

In [42]:
x = np.array([[2,4,6],
            [4,7,23]])
y = np.array([[4,76],
             [3,7],
             [2,6]])

z = np.dot(x,y)
z

array([[ 32, 216],
       [ 83, 491]])

In [47]:
def naive_vector_dot(x,y) :
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0
    
    for i in range(x.shape[0]) :
        z += x[i] * y[i]
        
    return z

In [48]:
def naive_matrix_dot (x,y) :
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    
    for i in range(x.shape[0]) :
        for j in range(y.shape[1]) :
            row_x = x[i, :]
            column_y = y[:,j]
            z[i,j] = naive_vector_dot(row_x, column_y)
            
    return z

In [49]:
naive_matrix_dot(x,y)

array([[ 32., 216.],
       [ 83., 491.]])

# tensor shape transformation

In [52]:
x = x.T
x

array([[ 2,  4],
       [ 4,  7],
       [ 6, 23]])

In [53]:
print(x.shape)

(3, 2)


In [56]:
x = x.reshape((6,1))
print(x)
print('shape : ',x.shape)

[[ 2]
 [ 4]
 [ 4]
 [ 7]
 [ 6]
 [23]]
shape :  (6, 1)


In [57]:
x = x.reshape((2,3))
print(x)
print('shape : ',x.shape)

[[ 2  4  4]
 [ 7  6 23]]
shape :  (2, 3)
